default_schema: login
aliases:
  pin: 0-9]{8}
  phrase: '[:word:](-[:word:]){4}'
  alnum: '[A-Za-z0-9]{18}'
  mobile: '[a-z0-9]{24}'
  login: '[!-~]{12}'
  apple: '[:Word:](-[:word:]){3}[0-9!-/]'
sites:
  apple.com: apple
  google.com: mobile
  iphone.local:
    schema: pin
    increment: 1
