default_schema: login
use_keyring: true
aliases:
  alnum: '[A-Za-z0-9]{18}'
  apple: '[:Word:](-[:word:]){3}[0-9!-/]'
  login: '[!-~]{12}'
  mobile: '[a-z0-9]{24}'
  phrase: '[:word:](-[:word:]){4}'
  pin: '[0-9]{8}'
sites:
  apple.com: apple
  google.com: mobile
  iphone.local:
    schema: pin
    increment: 1
