version: 2
updates:
  - package-ecosystem: "cargo"
    labels: ["dependencies", "main"]
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    labels: ["dependencies", "v2-dev"]
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: v2-dev
    cooldown:
      default-days: 7
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: v2-dev
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
