# TODO(soon): add changelogs

[package]
name = "onepass"
version = "3.1.9"
categories = ["command-line-utilities"]
edition.workspace = true
keywords = ["password", "cryptography", "deterministic"]
license = "AGPL-3.0-only"
readme = "README.md"
repository.workspace = true
description = "A mostly-stateless deterministic password manager"

exclude = [
    ".githook/*",
    ".github/**",
    ".gitignore",
    "LICENSE-AGPL",
    "LICENSE-Apache",
    "data/onepass.entitlements",
    "example/**",
    "onepass.provisionprofile",
]

[workspace]
resolver = "3"
members = ["crates/base", "crates/conf", "crates/seed"]

[workspace.package]
edition = "2024"
repository = "https://github.com/mrdomino/onepass"

[workspace.dependencies]
blake2 = { version = "0.11.0-rc.6", default-features = false }
hex = { version = "0.4.3", default-features = false }
onepass-base = { version = "0.2.0", path = "crates/base" }
onepass-conf = { version = "0.8.0", path = "crates/conf" }
onepass-seed = { version = "0.4.3", path = "crates/seed" }
secrecy = "0.10.3"
tempfile = "3.27.0"

[features]
default = [
    "keyring",
    "readpass-vendored",
]
keyring = [
    "apple-native-keyring-store/keychain",
    "dep:windows-native-keyring-store",
    "dep:dbus-secret-service-keyring-store",
]
macos-biometry = ["apple-native-keyring-store/protected"]
readpass-libbsd = ["readpassphrase-3/libbsd-static"]
readpass-vendored = ["readpassphrase-3/linux-vendored"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
strip = true

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "env", "unicode", "wrap_help"] }
keyring-core = "^1.0.0"
onepass-conf.workspace = true
onepass-seed.workspace = true
secrecy.workspace = true

[dependencies.readpassphrase-3]
version = "1.0.2"
default-features = false
features = [
    "windows-vendored",
    "zeroize",
]

[target.'cfg(target_os = "linux")'.dependencies]
dbus-secret-service-keyring-store = {
    version = "^1.0.0",
    features = ["crypto-openssl"],
    optional = true,
}

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "^1.0.1", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = { version = "^1.1.0", optional = true }

[dev-dependencies]
tempfile.workspace = true
