//! This crate implements arbitrary deterministic secret generation from a fixed seed password.
//!
//! The core, basic idea here is that a password schema should be enumerable: e.g. the schema
//! `[a-z]` generates 26 different passwords, the first one is `'a'`, and the last is `'z'`. So
//! then if we can count the size of the universe of passwords generated by a schema, then we can
//! use a cryptographically secure pseudorandom number generator to sample it based on a
//! deterministic secret, yielding a deterministic output.
//!
//! The other main piece of this password generation scheme entails securely deriving a per-site
//! secret from a single seed password, thereby stretching one secret into an arbitrary number of
//! secrets. We do this by taking a [password hash][0] of the seed password against a salt that
//! consists of the full derivation parameters for the site in question; e.g. the site URL,
//! username, and the schema from which the password is generated. Any changes to the derivation
//! should therefore result in securely different secrets, meaning that generally a compromised
//! site password should reveal no information about either the seed password or other site
//! passwords.
//!
//! Combining these ideas then, usage of this library collapses the state for a password manager
//! from `O(n)` secret state, where n is the number of sites for which a user has passwords, to
//! `O(1)` secret state (the seed) plus `O(n)` non-secret state (the public site derivation
//! parameters.) This makes migration much easier and safer than with traditional password
//! managers; a user may simply upload or copy their site derivation info and write down or
//! memorize their seed password.
//!
//! A lot of this crate, then, is about canonical serialization of site parameters and schemas such
//! that derivation paths may be deterministically re-derived from configuration. E.g. we normalize
//! URLs and we specify a canonical formatting of password schemas.
//!
//! This scheme is designed to be user-extensible; crate users may add their own custom secret
//! generators to extend this library into other domains. This is done via
//! <code>[Generator]</code>s. A `Generator` may extend a password schema with specific extra
//! configuration, e.g. a hash of a word list, to ensure that derivations that are different
//! produce uncorrelated passwords.
//!
//! The derivation parameters saved per-site are the (mandatory) URL, an optional username, the
//! password schema, and a nonce (called the “increment” in this crate.) The purpose of the nonce
//! is to make it easy to rotate a site password if one is ever compromised, or to comply with
//! rotation policies; simply incrementing the nonce should yield an uncorrelated, new password for
//! that site from the same seed.
//!
//! ```no_run
//! use onepass_seed::site::Site;
//! # use secrecy::ExposeSecret;
//! let site = Site::new("google.com", None, "{words:4:-}", 0).unwrap();
//! let pw = site.password("seedpass").unwrap();
//! assert_eq!("jaywalker-diffused-verse-abdominal", pw.expose_secret());
//! ```
//!
//! For more information on the schema language see <code>[Expr]</code>.
//!
//! [0]: https://en.wikipedia.org/wiki/Bcrypt
//! [Generator]: expr::Generator
//! [Expr]: expr::Expr

mod crypto;
pub mod dict;
pub mod expr;
mod macros;
pub mod site;
pub mod url;

use core::{error::Error, fmt};

use crypto_bigint::NonZero;
pub use crypto_bigint::U256;
pub use secrecy::{ExposeSecret, ExposeSecretMut, SecretBox, SecretString};

use expr::{Context, Node, size::sizes};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[deprecated(since = "0.4.6", note = "going away with next major release")]
pub enum LegacyCountError {
    WouldPanic,
    Changed {
        old: NonZero<U256>,
        new: NonZero<U256>,
    },
}

/// Check whether the given schema changed with v3.3.0.
#[deprecated(since = "0.4.6", note = "going away with next major release")]
#[allow(deprecated)]
pub fn check_legacy_count(context: &Context, node: &Node) -> Result<(), LegacyCountError> {
    let s = sizes(context, node).ok_or(LegacyCountError::WouldPanic)?;
    if s.changed {
        return Err(LegacyCountError::Changed {
            old: s.old,
            new: s.new,
        });
    }
    Ok(())
}

pub(crate) fn entropy(n: &NonZero<U256>) -> f32 {
    let bits = n.bits_vartime();
    let top: u32 = if bits > 24 {
        (n.get() >> (bits - 24)).as_words()[0] as u32
    } else {
        (n.as_words()[0] as u32) << (24 - bits)
    };
    let m = (top as f32) / 8388608.0; // 2**23, m in [1, 2)
    (bits - 1) as f32 + m.log2()
}

#[allow(deprecated)]
impl fmt::Display for LegacyCountError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LegacyCountError::WouldPanic => f.write_str("would panic"),
            LegacyCountError::Changed { old, new } => {
                f.write_str("must be rotated")?;
                let old_entropy = entropy(old);
                let new_entropy = entropy(new);
                let diff = new_entropy - old_entropy;
                if diff != 0.0 {
                    write!(
                        f,
                        ", entropy diff (bits): {:.02}\told: {:.02}\tnew: {:.02}",
                        diff, old_entropy, new_entropy
                    )?;
                } else if old != new {
                    write!(f, ", size differs by {}", (**new - **old).to_words()[0])?;
                } else {
                    f.write_str(", internal sizes differ")?;
                }
                Ok(())
            }
        }
    }
}
#[allow(deprecated)]
impl Error for LegacyCountError {}

#[cfg(test)]
pub(crate) mod testing {
    use crypto_bigint::{NonZero, U256};
    use serde::{Deserialize, Deserializer, de};

    pub(crate) const COUNT_VECTORS: &str = include_str!("../data/count_vectors.toml");

    pub(crate) fn u256_from_be_hex<'de, D>(
        deserializer: D,
    ) -> Result<Option<NonZero<U256>>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        if s == "none" {
            return Ok(None);
        }
        let s = s.strip_prefix("0x").unwrap_or(&s);
        if s.len() != 64 || !s.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(de::Error::custom(
                "expected 64 hex characters (optionally prefixed with 0x)",
            ));
        }
        Ok(Some(NonZero::new(U256::from_be_hex(s)).unwrap()))
    }
}

#[cfg(test)]
mod tests {
    use serde::Deserialize;

    use super::{testing::*, *};

    #[derive(Deserialize)]
    struct Schema {
        name: String,
        schema: String,
        why: String,
        expect: String,
        #[serde(default)]
        display: String,
        #[serde(default, deserialize_with = "u256_from_be_hex")]
        old: Option<NonZero<U256>>,
        #[serde(default, deserialize_with = "u256_from_be_hex")]
        new: Option<NonZero<U256>>,
    }

    #[derive(Deserialize)]
    struct Schemata {
        schema: Vec<Schema>,
    }

    #[test]
    #[allow(deprecated)]
    fn test_vectors() {
        for s in toml::from_str::<Schemata>(COUNT_VECTORS).unwrap().schema {
            eprintln!("{}/{}", s.name, s.why);
            let node: Node = s.schema.parse().unwrap();
            let res = check_legacy_count(&Context::default(), &node);
            match res {
                Ok(()) => assert_eq!("ok", s.expect, "{res:?}"),
                Err(err) => {
                    assert_eq!(s.display, format!("{err}"));
                    match err {
                        LegacyCountError::WouldPanic => {
                            assert_eq!("would_panic", s.expect, "{err}")
                        }
                        LegacyCountError::Changed { old, new } => {
                            assert_eq!("changed", s.expect, "{err}");
                            assert_eq!(s.old.unwrap(), old, "old");
                            assert_eq!(s.new.unwrap(), new, "new");
                        }
                    }
                }
            }
        }
    }
}
