//! This crate implements arbitrary deterministic secret generation from a fixed seed password.
//!
//! The core, basic idea here is that a password schema should be enumerable: e.g. the schema
//! `[a-z]` generates 26 different passwords, the first one is `'a'`, and the last is `'z'`. So
//! then if we can count the size of the universe of passwords generated by a schema, then we can
//! use a cryptographically secure pseudorandom number generator to sample it based on a
//! deterministic secret.
//!
//! The other main piece of this password generation scheme entails securely deriving a per-site
//! secret from a single seed password, thereby stretching one secret into an arbitrary number of
//! secrets. We do this by taking a [password hash][0] of the seed password against a salt that
//! consists of the full derivation parameters for the site in question; e.g. the site URL,
//! username, and the schema from which the password is generated. Any changes to the derivation
//! should therefore result in securely different secrets, meaning that generally a compromised
//! site password should reveal no information about either the seed password or other site
//! passwords.
//!
//! Combining these ideas then, usage of this library collapses the state for a password manager
//! from `O(n)` secret state, where n is the number of sites for which a user has passwords, to
//! `O(1)` secret state (the seed) plus `O(n)` non-secret state (the public site derivation
//! parameters.) This makes migration much easier and safer than with traditional password
//! managers; a user may simply upload or copy their site derivation info, and memorize their seed
//! password.
//!
//! A lot of this crate, then is about canonical serialization of site parameters and schemas such
//! that derivation paths may be deterministically re-derived from configuration. E.g. we normalize
//! URLs and we specify a canonical formatting of password schemas.
//!
//! This scheme is designed to be user-extensible; crate users may add their own custom secret
//! generators to extend this library into other domains. This is done via
//! [`Generator`]s. A [`Generator`] may extend a password schema with specific extra configuration,
//! e.g. a hash of a word list, to ensure that derivations that are different produce uncorrelated
//! passwords.
//!
//! For more on the cryptographic primitives and the specific parameters used for password hashing,
//! see [`crypto`]. For more on the schema language, see [`expr`] and especially [`expr::parse`].
//! For URL normalization see [`url`].
//!
//! ```
//! use onepass_seed::site::Site;
//! let site = Site::new("google.com", None, "{words:4:-}", 0).unwrap();
//! assert_eq!("jaywalker-diffused-verse-abdominal", &*site.password("seedpass").unwrap());
//! ```
//!
//! [0]: https://en.wikipedia.org/wiki/Bcrypt
//! [`Generator`]: expr::generator::Generator

pub mod crypto;
pub mod dict;
pub mod expr;
pub mod fmt;
pub mod site;
pub mod url;
