#!/bin/sh
set -eu
# Hook courtesy of:
# <https://deaddabe.fr/blog/2021/09/29/git-pre-commit-hook-for-rust-projects/>
# To use:
#     git config --local core.hooksPath .githooks/
#
if ! cargo fmt --all -- --check
then
  echo 'There are some code style issues.' >&2
  echo 'Run cargo fmt first.' >&2
  exit 1
fi

if ! cargo clippy --locked --all-targets -- -D warnings
then
  echo 'There are some clippy issues.'
  exit 1
fi

if ! cargo test --locked --all
then
  echo 'There are some test issues.'
  exit 1
fi
