name: Build

on:
  pull_request:
  push:
    branches: [main, v2-dev]
  workflow_call:
    inputs:
      release:
        default: false
        type: boolean
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        type: string
        required: false

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os:   macos
            arch: aarch64
          - os:   ubuntu
            arch: aarch64
            runner: ubuntu-24.04-arm
          - os:   ubuntu
            arch: x86_64
          - os:   windows
            arch: aarch64
            runner: windows-11-arm
          - os:     windows
            arch:   x86_64

          - os:   ubuntu
            arch: x86_64
            musl: true
          - os:   ubuntu
            arch: aarch64
            runner: ubuntu-24.04-arm
            musl: true

    runs-on: ${{ matrix.runner != '' && matrix.runner || format('{0}-latest', matrix.os)}}

    steps:
    - name: setup environment
      id: env
      shell: bash
      run: |
        set -u

        if [[ "${MATRIX_MUSL}" == true ]]; then
          osname=unknown-linux-musl
        else
          case "${MATRIX_OS}" in
            macos)   osname=apple-darwin        ;;
            ubuntu)  osname=unknown-linux-gnu   ;;
            windows) osname=pc-windows-msvc     ;;
          esac
        fi
        target=${MATRIX_ARCH}-$osname
        echo CARGO_BUILD_TARGET=$target >> $GITHUB_ENV

        if [[ "${INPUTS_RELEASE}" == true ]]; then
          outdir=release
          ( echo profile=release
            echo retention_days=90
          ) >> $GITHUB_OUTPUT
        else
          outdir=debug
          ( echo profile=dev
            echo retention_days=7
          ) >> $GITHUB_OUTPUT
        fi

        if [[ "${MATRIX_MUSL}" == true ]]; then
          echo pkgs=musl-tools >> $GITHUB_OUTPUT
          echo TARGET_CC=musl-gcc >> $GITHUB_ENV
        elif [[ "${MATRIX_OS}" == ubuntu ]]; then
          echo pkgs='libbsd-dev libdbus-1-dev' >> $GITHUB_OUTPUT
        fi

        if [[ "${MATRIX_MUSL}" == true ]]; then
          features=' --no-default-features --features=readpass-vendored'
        elif [[ "${MATRIX_OS}" == macos && "${INPUTS_RELEASE}" == true ]]; then
          features=' --no-default-features --features=macos-biometry'
        elif [[ "${MATRIX_OS}" == ubuntu && "${INPUTS_RELEASE}" == true ]]; then
          features=' --no-default-features --features=keyring,readpass-libbsd'
        else
          features=
        fi
        echo features=$features >> $GITHUB_OUTPUT

        suffix=
        if [[ "${MATRIX_OS}" == windows ]]; then
          suffix=.exe
        fi
        echo binary_path=target/$target/$outdir/onepass$suffix >> $GITHUB_OUTPUT
        echo binary_name=onepass-$target >> $GITHUB_OUTPUT

      env:
        MATRIX_ARCH: ${{ matrix.arch }}
        MATRIX_MUSL: ${{ matrix.musl }}
        MATRIX_OS: ${{ matrix.os }}
        INPUTS_RELEASE: ${{ inputs.release }}

    - name: install system dependencies
      if: ${{ steps.env.outputs.pkgs != '' }}
      run: |
        sudo sh -eu <<EOF
        apt-get update && apt-get install -yy --no-install-recommends \
          $PKGS
        EOF
      env:
        PKGS: ${{ steps.env.outputs.pkgs }}

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.tag || github.ref }}
        persist-credentials: false
    - run: rustup toolchain install --profile minimal
    - run: rustup target add "$CARGO_BUILD_TARGET"
      if: matrix.musl
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      with:
        key: ${{ steps.env.outputs.profile }}

    - run: |
        cargo build --locked --profile "${ENV_PROFILE}" ${ENV_FEATURES}
      shell: bash
      env:
        ENV_PROFILE: ${{ steps.env.outputs.profile }}
        ENV_FEATURES: ${{ steps.env.outputs.features }}

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ steps.env.outputs.binary_name }}
        path: ${{ steps.env.outputs.binary_path }}
        retention-days: ${{ steps.env.outputs.retention_days }}

    - run: |
        cargo test --profile dev ${ENV_FEATURES} -- --include-ignored
      if: ${{ !inputs.release }}
      env:
        ENV_FEATURES: ${{ steps.env.outputs.features }}
