name: Build

on:
  pull_request:
  push:
    branches: [main, v2-dev]
  workflow_call:
    inputs:
      release:
        default: false
        type: boolean
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        type: string
        required: false

permissions:
  contents: read

jobs:

  build:
    name: Build
    strategy:
      matrix:
        include:
          - { runner: macos-latest }
          - { runner: ubuntu-24.04-arm }
          - { runner: ubuntu-24.04-arm, libc: musl }
          - { runner: ubuntu-latest }
          - { runner: ubuntu-latest, libc: musl }
          - { runner: windows-11-arm }
          - { runner: windows-latest }
    runs-on: ${{ matrix.runner }}

    steps:
    - name: setup environment
      id: env
      shell: bash
      run: |
        set -u

        arch=x86_64
        if [[ "${os:=${MATRIX_RUNNER%%-*}}" == "macos" ||
              "${MATRIX_RUNNER##*-}" == arm ]]; then
          arch=aarch64
        fi
        echo arch=$arch >> $GITHUB_OUTPUT

        if [[ "${MATRIX_LIBC}" == musl ]]; then
          osname=unknown-linux-musl
        else
          case "${os}" in
            macos)   osname=apple-darwin        ;;
            ubuntu)  osname=unknown-linux-gnu   ;;
            windows) osname=pc-windows-msvc     ;;
          esac
        fi
        target=${arch}-${osname}
        echo "CARGO_BUILD_TARGET=${target}" >> $GITHUB_ENV

        if [[ "${INPUTS_RELEASE}" == true ]]; then
          outdir=release
          ( echo profile=release
            echo retention_days=90
          ) >> $GITHUB_OUTPUT
        else
          outdir=debug
          ( echo profile=dev
            echo retention_days=7
          ) >> $GITHUB_OUTPUT
        fi

        if [[ "${MATRIX_LIBC}" == musl ]]; then
          echo pkgs=musl-tools >> $GITHUB_OUTPUT
          echo TARGET_CC=musl-gcc >> $GITHUB_ENV
        elif [[ "${os}" == ubuntu ]]; then
          echo pkgs='libbsd-dev libdbus-1-dev' >> $GITHUB_OUTPUT
        fi

        if [[ "${MATRIX_LIBC}" == musl ]]; then
          features='--no-default-features --features=readpass-vendored'
        elif [[ "${os}" == macos && "${INPUTS_RELEASE}" == true ]]; then
          features='--no-default-features --features=macos-biometry'
        elif [[ "${os}" == ubuntu && "${INPUTS_RELEASE}" == true ]]; then
          features='--no-default-features --features=keyring,readpass-libbsd'
        else
          features=
        fi
        echo "features=$features" >> $GITHUB_OUTPUT

        suffix=
        if [[ "${os}" == windows ]]; then
          suffix=.exe
        fi
        ( echo "binary_path=target/$target/$outdir/onepass$suffix"
          echo "binary_name=onepass-$target"
        ) >> $GITHUB_OUTPUT

      env:
        MATRIX_RUNNER: ${{ matrix.runner }}
        MATRIX_LIBC: ${{ matrix.libc }}
        INPUTS_RELEASE: ${{ inputs.release }}

    - name: install system dependencies
      if: ${{ steps.env.outputs.pkgs != '' }}
      run: |
        sudo sh -eu <<EOF
        apt-get update && apt-get install -yy --no-install-recommends \
          $PKGS
        EOF
      env:
        PKGS: ${{ steps.env.outputs.pkgs }}

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.tag || github.ref }}
        persist-credentials: false
    - run: rustup toolchain install --profile minimal
    - run: rustup target add "$CARGO_BUILD_TARGET"
      if: ${{ matrix.libc == 'musl' }}
    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      if: ${{ !inputs.release }}

    - run: cargo build --locked --profile "${ENV_PROFILE}" ${ENV_FEATURES}
      shell: bash
      env:
        ENV_FEATURES: ${{ steps.env.outputs.features }}
        ENV_PROFILE: ${{ steps.env.outputs.profile }}

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ steps.env.outputs.binary_name }}
        path: ${{ steps.env.outputs.binary_path }}
        retention-days: ${{ steps.env.outputs.retention_days }}

    - run: cargo test --profile dev --all ${ENV_FEATURES} -- --include-ignored
      if: ${{ !inputs.release }}
      shell: bash
      env:
        ENV_FEATURES: ${{ steps.env.outputs.features }}

    - run: cargo publish --locked --dry-run --workspace
      if: ${{ inputs.release && matrix.libc != 'musl' }}
